name: savage chucky
favicon: null
layout_spectrum: 0.11697525042109191
typography_spectrum: 0.6691258191131055
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#3a538b'
    - '#738bb1'
    - '#a4bbdf'
  brandStrength: 0.25
  lightness: 0.25
  saturation: 0.4375
  rhythmicContrast: 0.6597525158431381
purpose: []
