name: savage chucky
favicon: null
layout_spectrum: 0.11697525042109191
typography_spectrum: 0.6691258191131055
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#a3c89d'
    - '#34403e'
    - '#f5fbef'
    - '#d82602'
  brandStrength: 0.40089481067843735
  lightness: 0.19682271336205304
  saturation: 0.242428885307163
  rhythmicContrast: 0.6597525158431381
purpose: []
